### ISSUE TITLE
Sysctl not persisting if run contains a reboot

### ISSUE THREAD

**Issue by ianbamforth** [weseek/chef-vpcnat#2]
This cookbook previously worked perfectly for me, but a recent change to my run list to include a reboot appears to have resulted in the systl net.ipv4.ip_forward setting not persisting.

I can't see how to do this with the 0.4 version of sysctl cookbook, is there any reason not to upgrade to the latest?  0.6.2 has a recipe (::apply) that immediately outputs the config changes.

**Comment by kouki-o** [comment]
@ianbamforth 
Thanks for reporting a issue. will push a new version.

**Comment by kouki-o** [comment]
@ianbamforth 
v1.2.8 released. https://github.com/weseek/chef-vpcnat/releases/tag/v1.2.8
Please give it a try.
